import { ajisAnak } from '@/db/schema';
import { eq } from 'drizzle-orm';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

interface DesaData {
  id: number | bigint;
  kode: string;
  [key: string]: unknown;
}

interface KantorData {
  id: number | bigint;
  kode: string;
  [key: string]: unknown;
}

interface WilayahData {
  id: number | bigint;
  kodeLama: number;
  [key: string]: unknown;
}

interface SdmData {
  id: number | bigint;
  kodeLama: number;
  [key: string]: unknown;
}

interface GeographicData {
  desa: DesaData[];
}

interface OrganizationData {
  kantor: KantorData[];
  wilayah: WilayahData[];
}

export async function seedAnak(
  db: PostgresJsDatabase,
  geographicData: GeographicData,
  organizationData: OrganizationData,
  sdmData: SdmData[]
) {
  console.log('👶 Seeding anak data...');

  const { desa } = geographicData;
  const { kantor, wilayah } = organizationData;

  // Create maps for ID lookup
  const desaByKode = new Map(desa.map((d: DesaData) => [d.kode, d]));
  const kantorByKode = new Map(kantor.map((k: KantorData) => [k.kode, k]));
  const wilayahByKodeLama = new Map(wilayah.map((w: WilayahData) => [w.kodeLama, w]));
  const sdmByKodeLama = new Map(sdmData.map((s: SdmData) => [s.kodeLama, s]));

  // Helper functions
  const getDesaId = (kode: string) => {
    const d = desaByKode.get(kode);
    if (!d) throw new Error(`Desa with kode ${kode} not found`);
    return Number(d.id);
  };

  const getKantorId = (kode: string) => {
    const k = kantorByKode.get(kode);
    if (!k) throw new Error(`Kantor with kode ${kode} not found`);
    return Number(k.id);
  };

  const getWilayahId = (kodeLama: number) => {
    const w = wilayahByKodeLama.get(kodeLama);
    if (!w) throw new Error(`Wilayah with kodeLama ${kodeLama} not found`);
    return Number(w.id);
  };

  const getSdmId = (kodeLama: number) => {
    const s = sdmByKodeLama.get(kodeLama);
    if (!s) throw new Error(`SDM with kodeLama ${kodeLama} not found`);
    return Number(s.id);
  };

  // Anak data (12 rows - 1 per wilayah for RBAC testing + 3 additional)
  const anakData = [
    // Wilayah Jakarta Pusat (wilayah kodeLama 1, kantor K001, desa 310101001, sdm kodeLama 1)
    {
      kodeAnak: 'ANK-JKT-001',
      nik: '3171234567890001',
      namaLengkap: 'Ahmad Fauzi',
      namaPanggilan: 'Fauzi',
      agama: 'Islam',
      jnsKel: 'l',
      tempatLahir: 'Jakarta',
      tglLahir: '2012-05-15',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Sudirman No. 123, Jakarta Pusat',
      desaId: getDesaId('310101001'),
      jenjangPendidikan: 'SD',
      kelas: '5',
      namaSekolah: 'SDN Gambir 01',
      alamatSekolah: 'Jl. Gambir No. 1, Jakarta Pusat',
      noRekening: '1234567890',
      pemilikRekening: 'Ahmad Fauzi',
      namaBank: 'BCA',
      nilai: 'A',
      pelajaranFavorit: 'Matematika',
      jarakRumah: '2 km',
      alatTransportasi: 'Motor',
      hobi: 'Sepak bola',
      prestasi: 'Juara 1 Lomba Matematika Sekolah',
      noKartuKeluarga: '3171234567890001',
      asnaf: 'Dhuafa',
      statusOrtu: 'Yatim Piatu',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(1),
      kantorId: getKantorId('K001'),
      sdmWilayahId: getSdmId(1),
      namaMentorManual: 'Budi Santoso',
      tglTerdaftar: '2020-01-15',
      tglPengajuan: '2020-01-10',
      namaLengkapAyah: 'Ahmad Hidayat',
      alamatAyah: 'Jl. Sudirman No. 123, Jakarta Pusat',
      pekerjaanAyah: 'Wiraswasta',
      penghasilanAyah: '2000000.00',
      tglKematianAyah: '2018-06-20',
      penyebabKematianAyah: 'Sakit',
      namaLengkapIbu: 'Siti Aminah',
      alamatIbu: 'Jl. Sudirman No. 123, Jakarta Pusat',
      pekerjaanIbu: 'Ibu Rumah Tangga',
      penghasilanIbu: '1500000.00',
      tglKematianIbu: '2019-03-15',
      penyebabKematianIbu: 'Kecelakaan',
      namaLengkapWali: 'H. Abdullah',
      alamatWali: 'Jl. Sudirman No. 124, Jakarta Pusat',
      pekerjaanWali: 'Pedagang',
      penghasilanWali: '3000000.00',
      telpDihubungi: '081234567890',
      atasNama: 'H. Abdullah',
      hubunganKerabat: 'Paman',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-JKT',
      tinggalBersama: 'Paman',
      namaTinggal: 'H. Abdullah',
      ketTinggal: 'Tinggal bersama paman sejak yatim piatu',
      penghasilanTinggal: '3000000',
      pekerjaanTinggal: 'Pedagang',
      tidakSerumahOrtu: 'y',
    },
    // Wilayah Jakarta Selatan (wilayah kodeLama 2, kantor K001, desa 310101002, sdm kodeLama 2)
    {
      kodeAnak: 'ANK-JKT-002',
      nik: '3171234567890002',
      namaLengkap: 'Siti Nurhaliza',
      namaPanggilan: 'Liza',
      agama: 'Islam',
      jnsKel: 'p',
      tempatLahir: 'Jakarta',
      tglLahir: '2013-08-20',
      anakKe: 2,
      dariSaudara: 3,
      alamat: 'Jl. Fatmawati No. 100, Jakarta Selatan',
      desaId: getDesaId('310101002'),
      jenjangPendidikan: 'SD',
      kelas: '4',
      namaSekolah: 'SDN Kebon Kelapa 01',
      alamatSekolah: 'Jl. Kebon Kelapa No. 1, Jakarta Selatan',
      noRekening: '2345678901',
      pemilikRekening: 'Siti Nurhaliza',
      namaBank: 'BNI',
      nilai: 'A',
      pelajaranFavorit: 'Bahasa Inggris',
      jarakRumah: '1.5 km',
      alatTransportasi: 'Motor',
      hobi: 'Membaca',
      prestasi: 'Juara 2 Lomba Baca Puisi',
      noKartuKeluarga: '3171234567890002',
      asnaf: 'Yatim',
      statusOrtu: 'Yatim',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(2),
      kantorId: getKantorId('K001'),
      sdmWilayahId: getSdmId(2),
      namaMentorManual: 'Dewi Sartika',
      tglTerdaftar: '2020-02-20',
      tglPengajuan: '2020-02-15',
      namaLengkapAyah: 'Rahmat Hidayat',
      alamatAyah: 'Jl. Fatmawati No. 100, Jakarta Selatan',
      pekerjaanAyah: 'Karyawan Swasta',
      penghasilanAyah: '3000000.00',
      tglKematianAyah: '2017-09-10',
      penyebabKematianAyah: 'Sakit',
      namaLengkapIbu: 'Ratna Sari',
      alamatIbu: 'Jl. Fatmawati No. 100, Jakarta Selatan',
      pekerjaanIbu: 'Guru Honorer',
      penghasilanIbu: '2000000.00',
      telpDihubungi: '081234567891',
      atasNama: 'Ratna Sari',
      hubunganKerabat: 'Ibu',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-JKT',
      tinggalBersama: 'Ibu',
      namaTinggal: 'Ratna Sari',
      ketTinggal: 'Tinggal bersama ibu',
      penghasilanTinggal: '2000000',
      pekerjaanTinggal: 'Guru Honorer',
      tidakSerumahOrtu: 'n',
    },
    // Wilayah Jakarta Barat (wilayah kodeLama 3, kantor K001, desa 310101003, sdm kodeLama 3)
    {
      kodeAnak: 'ANK-JKT-003',
      nik: '3171234567890003',
      namaLengkap: 'Budi Pratama',
      namaPanggilan: 'Budi',
      agama: 'Islam',
      jnsKel: 'l',
      tempatLahir: 'Jakarta',
      tglLahir: '2011-11-25',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Palmerah No. 50, Jakarta Barat',
      desaId: getDesaId('310101003'),
      jenjangPendidikan: 'SMP',
      kelas: '7',
      namaSekolah: 'SMPN 1 Petojo Utara',
      alamatSekolah: 'Jl. Petojo Utara No. 10, Jakarta Barat',
      noRekening: '3456789012',
      pemilikRekening: 'Budi Pratama',
      namaBank: 'Mandiri',
      nilai: 'B',
      pelajaranFavorit: 'IPA',
      jarakRumah: '3 km',
      alatTransportasi: 'Motor',
      hobi: 'Bermain Game',
      prestasi: 'Juara 3 Lomba Sains',
      noKartuKeluarga: '3171234567890003',
      asnaf: 'Dhuafa',
      statusOrtu: 'Kedua Orang Tua Hidup',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'tidak',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'tidak',
      wilayahPembinaanId: getWilayahId(3),
      kantorId: getKantorId('K001'),
      sdmWilayahId: getSdmId(3),
      namaMentorManual: 'Agus Setiawan',
      tglTerdaftar: '2020-03-25',
      tglPengajuan: '2020-03-20',
      namaLengkapAyah: 'Joko Susilo',
      alamatAyah: 'Jl. Palmerah No. 50, Jakarta Barat',
      pekerjaanAyah: 'Supir Taksi',
      penghasilanAyah: '2500000.00',
      namaLengkapIbu: 'Sri Mulyani',
      alamatIbu: 'Jl. Palmerah No. 50, Jakarta Barat',
      pekerjaanIbu: 'Ibu Rumah Tangga',
      penghasilanIbu: '0.00',
      telpDihubungi: '081234567892',
      atasNama: 'Joko Susilo',
      hubunganKerabat: 'Ayah',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-JKT',
      tinggalBersama: 'Orang Tua',
      namaTinggal: 'Joko Susilo',
      ketTinggal: 'Tinggal bersama orang tua',
      penghasilanTinggal: '2500000',
      pekerjaanTinggal: 'Supir Taksi',
      tidakSerumahOrtu: 'n',
    },
    // Wilayah Cibinong (wilayah kodeLama 4, kantor K002, desa 320101001, sdm kodeLama 4)
    {
      kodeAnak: 'ANK-BDG-001',
      nik: '3201234567890001',
      namaLengkap: 'Rina Melati',
      namaPanggilan: 'Melati',
      agama: 'Islam',
      jnsKel: 'p',
      tempatLahir: 'Bogor',
      tglLahir: '2011-12-01',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Raya Cibinong No. 200, Cibinong',
      desaId: getDesaId('320101001'),
      jenjangPendidikan: 'SMP',
      kelas: '8',
      namaSekolah: 'SMPN 1 Cibinong',
      alamatSekolah: 'Jl. Raya Cibinong No. 50, Cibinong',
      noRekening: '5566778899',
      pemilikRekening: 'Rina Melati',
      namaBank: 'BRI',
      nilai: 'A',
      pelajaranFavorit: 'Matematika',
      jarakRumah: '1 km',
      alatTransportasi: 'Motor',
      hobi: 'Menari',
      prestasi: 'Juara 1 Lomba Tari Daerah',
      noKartuKeluarga: '3201234567890001',
      asnaf: 'Yatim',
      statusOrtu: 'Yatim',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(4),
      kantorId: getKantorId('K002'),
      sdmWilayahId: getSdmId(4),
      namaMentorManual: 'Siti Aminah',
      tglTerdaftar: '2020-04-10',
      tglPengajuan: '2020-04-05',
      namaLengkapAyah: 'Hendro Wibowo',
      alamatAyah: 'Jl. Raya Cibinong No. 200, Cibinong',
      pekerjaanAyah: 'Petani',
      penghasilanAyah: '1500000.00',
      tglKematianAyah: '2016-08-15',
      penyebabKematianAyah: 'Kecelakaan Kerja',
      namaLengkapIbu: 'Sri Wahyuni',
      alamatIbu: 'Jl. Raya Cibinong No. 200, Cibinong',
      pekerjaanIbu: 'Buruh Tani',
      penghasilanIbu: '1000000.00',
      telpDihubungi: '081234567893',
      atasNama: 'Sri Wahyuni',
      hubunganKerabat: 'Ibu',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-BDG',
      tinggalBersama: 'Ibu',
      namaTinggal: 'Sri Wahyuni',
      ketTinggal: 'Tinggal bersama ibu',
      penghasilanTinggal: '1000000',
      pekerjaanTinggal: 'Buruh Tani',
      tidakSerumahOrtu: 'n',
    },
    // Wilayah Citeureup (wilayah kodeLama 5, kantor K002, desa 320101002, sdm kodeLama 5)
    {
      kodeAnak: 'ANK-BDG-002',
      nik: '3201234567890002',
      namaLengkap: 'Dedi Kurniawan',
      namaPanggilan: 'Dedi',
      agama: 'Islam',
      jnsKel: 'l',
      tempatLahir: 'Citeureup',
      tglLahir: '2009-03-18',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Citeureup No. 88, Citeureup',
      desaId: getDesaId('320101002'),
      jenjangPendidikan: 'SMP',
      kelas: '9',
      namaSekolah: 'SMPN 1 Citeureup',
      alamatSekolah: 'Jl. Citeureup No. 30, Citeureup',
      noRekening: '4455667788',
      pemilikRekening: 'Dedi Kurniawan',
      namaBank: 'Mandiri',
      nilai: 'B',
      pelajaranFavorit: 'IPA',
      jarakRumah: '2.5 km',
      alatTransportasi: 'Sepeda',
      hobi: 'Bermain Sepak Bola',
      prestasi: 'Juara 2 Lomba Futsal Sekolah',
      noKartuKeluarga: '3201234567890002',
      asnaf: 'Dhuafa',
      statusOrtu: 'Kedua Orang Tua Hidup',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'tidak',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'tidak',
      wilayahPembinaanId: getWilayahId(5),
      kantorId: getKantorId('K002'),
      sdmWilayahId: getSdmId(5),
      namaMentorManual: 'Joko Susilo',
      tglTerdaftar: '2020-05-20',
      tglPengajuan: '2020-05-15',
      namaLengkapAyah: 'Supriyanto',
      alamatAyah: 'Jl. Citeureup No. 88, Citeureup',
      pekerjaanAyah: 'Buruh Pabrik',
      penghasilanAyah: '2200000.00',
      namaLengkapIbu: 'Sri Mulyani',
      alamatIbu: 'Jl. Citeureup No. 88, Citeureup',
      pekerjaanIbu: 'Ibu Rumah Tangga',
      penghasilanIbu: '0.00',
      telpDihubungi: '081234567894',
      atasNama: 'Supriyanto',
      hubunganKerabat: 'Ayah',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-BDG',
      tinggalBersama: 'Orang Tua',
      namaTinggal: 'Supriyanto',
      ketTinggal: 'Tinggal bersama orang tua',
      penghasilanTinggal: '2200000',
      pekerjaanTinggal: 'Buruh Pabrik',
      tidakSerumahOrtu: 'n',
    },
    // Wilayah Gunung Putri (wilayah kodeLama 6, kantor K002, desa 320101003, sdm kodeLama 6)
    {
      kodeAnak: 'ANK-BDG-003',
      nik: '3201234567890003',
      namaLengkap: 'Eko Prasetyo',
      namaPanggilan: 'Eko',
      agama: 'Islam',
      jnsKel: 'l',
      tempatLahir: 'Gunung Putri',
      tglLahir: '2010-07-30',
      anakKe: 2,
      dariSaudara: 3,
      alamat: 'Jl. Gunung Putri No. 75, Gunung Putri',
      desaId: getDesaId('320101003'),
      jenjangPendidikan: 'SMA',
      kelas: '10',
      namaSekolah: 'SMAN 1 Gunung Putri',
      alamatSekolah: 'Jl. Gunung Putri No. 25, Gunung Putri',
      noRekening: '6677889900',
      pemilikRekening: 'Eko Prasetyo',
      namaBank: 'BCA',
      nilai: 'A',
      pelajaranFavorit: 'Matematika',
      jarakRumah: '2 km',
      alatTransportasi: 'Motor',
      hobi: 'Renang',
      prestasi: 'Juara 1 Lomba Renang Kabupaten',
      noKartuKeluarga: '3201234567890003',
      asnaf: 'Yatim Piatu',
      statusOrtu: 'Yatim Piatu',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(6),
      kantorId: getKantorId('K002'),
      sdmWilayahId: getSdmId(6),
      namaMentorManual: 'Hendra Wijaya',
      tglTerdaftar: '2020-06-15',
      tglPengajuan: '2020-06-10',
      namaLengkapAyah: 'Sutrisno',
      alamatAyah: 'Jl. Gunung Putri No. 75, Gunung Putri',
      pekerjaanAyah: 'Pedagang Sayur',
      penghasilanAyah: '1800000.00',
      tglKematianAyah: '2015-12-05',
      penyebabKematianAyah: 'Sakit',
      namaLengkapIbu: 'Sri Wahyuni',
      alamatIbu: 'Jl. Gunung Putri No. 75, Gunung Putri',
      pekerjaanIbu: 'Penjahit',
      penghasilanIbu: '1200000.00',
      tglKematianIbu: '2016-04-20',
      penyebabKematianIbu: 'Kecelakaan',
      namaLengkapWali: 'H. Mansur',
      alamatWali: 'Jl. Gunung Putri No. 76, Gunung Putri',
      pekerjaanWali: 'Pedagang',
      penghasilanWali: '2500000.00',
      telpDihubungi: '081234567895',
      atasNama: 'H. Mansur',
      hubunganKerabat: 'Paman',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-BDG',
      tinggalBersama: 'Paman',
      namaTinggal: 'H. Mansur',
      ketTinggal: 'Tinggal bersama paman sejak yatim piatu',
      penghasilanTinggal: '2500000',
      pekerjaanTinggal: 'Pedagang',
      tidakSerumahOrtu: 'y',
    },
    // Wilayah Johan Pahlawan (wilayah kodeLama 7, kantor K003, desa 110101001, sdm kodeLama 7)
    {
      kodeAnak: 'ANK-ACEH-001',
      nik: '1101234567890001',
      namaLengkap: 'Teuku Rizky',
      namaPanggilan: 'Rizky',
      agama: 'Islam',
      jnsKel: 'l',
      tempatLahir: 'Meulaboh',
      tglLahir: '2010-04-12',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Johan Pahlawan No. 50, Meulaboh',
      desaId: getDesaId('110101001'),
      jenjangPendidikan: 'SMA',
      kelas: '11',
      namaSekolah: 'SMA Negeri 1 Johan Pahlawan',
      alamatSekolah: 'Jl. Johan Pahlawan No. 10, Meulaboh',
      noRekening: '3344556677',
      pemilikRekening: 'Teuku Rizky',
      namaBank: 'BRI Syariah',
      nilai: 'A',
      pelajaranFavorit: 'Fisika',
      jarakRumah: '3 km',
      alatTransportasi: 'Motor',
      hobi: 'Renang',
      prestasi: 'Juara 1 Lomba Renang Provinsi',
      noKartuKeluarga: '1101234567890001',
      asnaf: 'Dhuafa',
      statusOrtu: 'Kedua Orang Tua Hidup',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(7),
      kantorId: getKantorId('K003'),
      sdmWilayahId: getSdmId(7),
      namaMentorManual: 'Teuku Iskandar',
      tglTerdaftar: '2020-07-10',
      tglPengajuan: '2020-07-05',
      namaLengkapAyah: 'Teuku Ibrahim',
      alamatAyah: 'Jl. Johan Pahlawan No. 50, Meulaboh',
      pekerjaanAyah: 'Nelayan',
      penghasilanAyah: '2500000.00',
      namaLengkapIbu: 'Cut Nyak Meutia',
      alamatIbu: 'Jl. Johan Pahlawan No. 50, Meulaboh',
      pekerjaanIbu: 'Penjual Ikan',
      penghasilanIbu: '2000000.00',
      telpDihubungi: '081234567896',
      atasNama: 'Teuku Ibrahim',
      hubunganKerabat: 'Ayah',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-ACEH',
      tinggalBersama: 'Orang Tua',
      namaTinggal: 'Teuku Ibrahim',
      ketTinggal: 'Tinggal bersama orang tua',
      penghasilanTinggal: '4500000',
      pekerjaanTinggal: 'Nelayan',
      tidakSerumahOrtu: 'n',
    },
    // Wilayah Jantho (wilayah kodeLama 8, kantor K003, desa 110201001, sdm kodeLama 8)
    {
      kodeAnak: 'ANK-ACEH-002',
      nik: '1101234567890002',
      namaLengkap: 'Cut Nurul Hidayah',
      namaPanggilan: 'Nurul',
      agama: 'Islam',
      jnsKel: 'p',
      tempatLahir: 'Jantho',
      tglLahir: '2013-08-22',
      anakKe: 2,
      dariSaudara: 3,
      alamat: 'Jl. Jantho No. 75, Jantho',
      desaId: getDesaId('110201001'),
      jenjangPendidikan: 'SD',
      kelas: '6',
      namaSekolah: 'SDN Jantho 01',
      alamatSekolah: 'Jl. Jantho No. 25, Jantho',
      noRekening: '7788990011',
      pemilikRekening: 'Cut Nurul Hidayah',
      namaBank: 'BRI',
      nilai: 'A',
      pelajaranFavorit: 'Bahasa Arab',
      jarakRumah: '1.5 km',
      alatTransportasi: 'Jalan Kaki',
      hobi: 'Membaca Al-Quran',
      prestasi: 'Juara 1 Lomba Mengaji',
      noKartuKeluarga: '1101234567890002',
      asnaf: 'Yatim',
      statusOrtu: 'Yatim',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(8),
      kantorId: getKantorId('K003'),
      sdmWilayahId: getSdmId(8),
      namaMentorManual: 'Siti Sarah',
      tglTerdaftar: '2020-10-15',
      tglPengajuan: '2020-10-10',
      namaLengkapAyah: 'Teuku Zulkarnain',
      alamatAyah: 'Jl. Jantho No. 75, Jantho',
      pekerjaanAyah: 'Petani',
      penghasilanAyah: '1800000.00',
      tglKematianAyah: '2017-11-30',
      penyebabKematianAyah: 'Sakit Jantung',
      namaLengkapIbu: 'Cut Meutia',
      alamatIbu: 'Jl. Jantho No. 75, Jantho',
      pekerjaanIbu: 'Penjahit',
      penghasilanIbu: '1200000.00',
      telpDihubungi: '081234567897',
      atasNama: 'Cut Meutia',
      hubunganKerabat: 'Ibu',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-ACEH',
      tinggalBersama: 'Ibu',
      namaTinggal: 'Cut Meutia',
      ketTinggal: 'Tinggal bersama ibu',
      penghasilanTinggal: '1200000',
      pekerjaanTinggal: 'Penjahit',
      tidakSerumahOrtu: 'n',
    },
    // Wilayah Samatiga (wilayah kodeLama 9, kantor K003, desa 110101002, sdm kodeLama 9)
    {
      kodeAnak: 'ANK-ACEH-003',
      nik: '1101234567890003',
      namaLengkap: 'Teuku Muhammad',
      namaPanggilan: 'Muhammad',
      agama: 'Islam',
      jnsKel: 'l',
      tempatLahir: 'Meulaboh',
      tglLahir: '2012-02-14',
      anakKe: 1,
      dariSaudara: 1,
      alamat: 'Jl. Samatiga No. 75, Samatiga',
      desaId: getDesaId('110101002'),
      jenjangPendidikan: 'SD',
      kelas: '5',
      namaSekolah: 'SDN Meulaboh 01',
      alamatSekolah: 'Jl. Samatiga No. 25, Meulaboh',
      noRekening: '8899001122',
      pemilikRekening: 'Teuku Muhammad',
      namaBank: 'BRI Syariah',
      nilai: 'A',
      pelajaranFavorit: 'Matematika',
      jarakRumah: '2 km',
      alatTransportasi: 'Motor',
      hobi: 'Sepak bola',
      prestasi: 'Juara 1 Lomba Matematika Sekolah',
      noKartuKeluarga: '1101234567890003',
      asnaf: 'Dhuafa',
      statusOrtu: 'Kedua Orang Tua Hidup',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(9),
      kantorId: getKantorId('K003'),
      sdmWilayahId: getSdmId(9),
      namaMentorManual: 'Teuku Ismail',
      tglTerdaftar: '2020-08-20',
      tglPengajuan: '2020-08-15',
      namaLengkapAyah: 'Teuku Budi',
      alamatAyah: 'Jl. Samatiga No. 75, Samatiga',
      pekerjaanAyah: 'Nelayan',
      penghasilanAyah: '2200000.00',
      namaLengkapIbu: 'Cut Fatimah',
      alamatIbu: 'Jl. Samatiga No. 75, Samatiga',
      pekerjaanIbu: 'Penjual Ikan',
      penghasilanIbu: '1800000.00',
      telpDihubungi: '081234567898',
      atasNama: 'Teuku Budi',
      hubunganKerabat: 'Ayah',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-ACEH',
      tinggalBersama: 'Orang Tua',
      namaTinggal: 'Teuku Budi',
      ketTinggal: 'Tinggal bersama orang tua',
      penghasilanTinggal: '4000000',
      pekerjaanTinggal: 'Nelayan',
      tidakSerumahOrtu: 'n',
    },
    // Additional anak for Jakarta Pusat (wilayah kodeLama 1, kantor K001, desa 310101001, sdm kodeLama 1)
    {
      kodeAnak: 'ANK-JKT-004',
      nik: '3171234567890004',
      namaLengkap: 'Rahmat Hidayat',
      namaPanggilan: 'Rahmat',
      agama: 'Islam',
      jnsKel: 'l',
      tempatLahir: 'Jakarta',
      tglLahir: '2011-03-10',
      anakKe: 2,
      dariSaudara: 3,
      alamat: 'Jl. Tanah Abang No. 50, Jakarta Pusat',
      desaId: getDesaId('310101001'),
      jenjangPendidikan: 'SD',
      kelas: '6',
      namaSekolah: 'SDN Tanah Abang 01',
      alamatSekolah: 'Jl. Tanah Abang No. 10, Jakarta Pusat',
      noRekening: '9988776655',
      pemilikRekening: 'Rahmat Hidayat',
      namaBank: 'BCA',
      nilai: 'B',
      pelajaranFavorit: 'IPA',
      jarakRumah: '1 km',
      alatTransportasi: 'Jalan Kaki',
      hobi: 'Catur',
      prestasi: 'Juara 2 Lomba Catur Sekolah',
      noKartuKeluarga: '3171234567890004',
      asnaf: 'Dhuafa',
      statusOrtu: 'Kedua Orang Tua Hidup',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'tidak',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'tidak',
      wilayahPembinaanId: getWilayahId(1),
      kantorId: getKantorId('K001'),
      sdmWilayahId: getSdmId(1),
      namaMentorManual: 'Budi Santoso',
      tglTerdaftar: '2020-11-01',
      tglPengajuan: '2020-10-25',
      namaLengkapAyah: 'Hendra Wijaya',
      alamatAyah: 'Jl. Tanah Abang No. 50, Jakarta Pusat',
      pekerjaanAyah: 'Karyawan Swasta',
      penghasilanAyah: '3500000.00',
      namaLengkapIbu: 'Dewi Kartika',
      alamatIbu: 'Jl. Tanah Abang No. 50, Jakarta Pusat',
      pekerjaanIbu: 'Guru',
      penghasilanIbu: '2500000.00',
      telpDihubungi: '081234567899',
      atasNama: 'Hendra Wijaya',
      hubunganKerabat: 'Ayah',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-JKT',
      tinggalBersama: 'Orang Tua',
      namaTinggal: 'Hendra Wijaya',
      ketTinggal: 'Tinggal bersama orang tua',
      penghasilanTinggal: '6000000',
      pekerjaanTinggal: 'Karyawan Swasta',
      tidakSerumahOrtu: 'n',
    },
    // Additional anak for Cibinong (wilayah kodeLama 4, kantor K002, desa 320101001, sdm kodeLama 4)
    {
      kodeAnak: 'ANK-BDG-004',
      nik: '3201234567890004',
      namaLengkap: 'Siti Rahayu',
      namaPanggilan: 'Rahayu',
      agama: 'Islam',
      jnsKel: 'p',
      tempatLahir: 'Bogor',
      tglLahir: '2012-06-15',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Raya Cibinong No. 150, Cibinong',
      desaId: getDesaId('320101001'),
      jenjangPendidikan: 'SD',
      kelas: '4',
      namaSekolah: 'SDN Cibinong 02',
      alamatSekolah: 'Jl. Raya Cibinong No. 75, Cibinong',
      noRekening: '1122334455',
      pemilikRekening: 'Siti Rahayu',
      namaBank: 'BRI',
      nilai: 'A',
      pelajaranFavorit: 'Bahasa Indonesia',
      jarakRumah: '0.5 km',
      alatTransportasi: 'Jalan Kaki',
      hobi: 'Menyanyi',
      prestasi: 'Juara 1 Lomba Nyanyi Sekolah',
      noKartuKeluarga: '3201234567890004',
      asnaf: 'Yatim',
      statusOrtu: 'Yatim',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(4),
      kantorId: getKantorId('K002'),
      sdmWilayahId: getSdmId(4),
      namaMentorManual: 'Siti Aminah',
      tglTerdaftar: '2020-12-01',
      tglPengajuan: '2020-11-25',
      namaLengkapAyah: 'Agus Pratama',
      alamatAyah: 'Jl. Raya Cibinong No. 150, Cibinong',
      pekerjaanAyah: 'Petani',
      penghasilanAyah: '1200000.00',
      tglKematianAyah: '2018-02-10',
      penyebabKematianAyah: 'Kecelakaan',
      namaLengkapIbu: 'Sri Wahyuni',
      alamatIbu: 'Jl. Raya Cibinong No. 150, Cibinong',
      pekerjaanIbu: 'Buruh Tani',
      penghasilanIbu: '800000.00',
      telpDihubungi: '081234567900',
      atasNama: 'Sri Wahyuni',
      hubunganKerabat: 'Ibu',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-BDG',
      tinggalBersama: 'Ibu',
      namaTinggal: 'Sri Wahyuni',
      ketTinggal: 'Tinggal bersama ibu',
      penghasilanTinggal: '800000',
      pekerjaanTinggal: 'Buruh Tani',
      tidakSerumahOrtu: 'n',
    },
    // Additional anak for Johan Pahlawan (wilayah kodeLama 7, kantor K003, desa 110101001, sdm kodeLama 7)
    {
      kodeAnak: 'ANK-ACEH-004',
      nik: '1101234567890004',
      namaLengkap: 'Cut Meutia',
      namaPanggilan: 'Meutia',
      agama: 'Islam',
      jnsKel: 'p',
      tempatLahir: 'Meulaboh',
      tglLahir: '2014-09-20',
      anakKe: 1,
      dariSaudara: 1,
      alamat: 'Jl. Johan Pahlawan No. 75, Meulaboh',
      desaId: getDesaId('110101001'),
      jenjangPendidikan: 'SD',
      kelas: '3',
      namaSekolah: 'SDN Johan Pahlawan 02',
      alamatSekolah: 'Jl. Johan Pahlawan No. 30, Meulaboh',
      noRekening: '5566778899',
      pemilikRekening: 'Cut Meutia',
      namaBank: 'BRI Syariah',
      nilai: 'A',
      pelajaranFavorit: 'Matematika',
      jarakRumah: '1 km',
      alatTransportasi: 'Motor',
      hobi: 'Menggambar',
      prestasi: 'Juara 1 Lomba Menggambar Sekolah',
      noKartuKeluarga: '1101234567890004',
      asnaf: 'Dhuafa',
      statusOrtu: 'Kedua Orang Tua Hidup',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: getWilayahId(7),
      kantorId: getKantorId('K003'),
      sdmWilayahId: getSdmId(7),
      namaMentorManual: 'Teuku Iskandar',
      tglTerdaftar: '2021-01-15',
      tglPengajuan: '2021-01-10',
      namaLengkapAyah: 'Teuku Budi',
      alamatAyah: 'Jl. Johan Pahlawan No. 75, Meulaboh',
      pekerjaanAyah: 'Nelayan',
      penghasilanAyah: '2800000.00',
      namaLengkapIbu: 'Cut Fatimah',
      alamatIbu: 'Jl. Johan Pahlawan No. 75, Meulaboh',
      pekerjaanIbu: 'Penjual Ikan',
      penghasilanIbu: '1500000.00',
      telpDihubungi: '081234567901',
      atasNama: 'Teuku Budi',
      hubunganKerabat: 'Ayah',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-ACEH',
      tinggalBersama: 'Orang Tua',
      namaTinggal: 'Teuku Budi',
      ketTinggal: 'Tinggal bersama orang tua',
      penghasilanTinggal: '4300000',
      pekerjaanTinggal: 'Nelayan',
      tidakSerumahOrtu: 'n',
    },
  ];

  // Insert anak (skip if already exists)
  await db.insert(ajisAnak).values(anakData).onConflictDoNothing();

  // Fetch all anak
  const insertedAnak = await db.select().from(ajisAnak).where(eq(ajisAnak.aktif, 'y'));
  console.log(`✅ Inserted ${insertedAnak.length} anak`);

  return insertedAnak;
}
