import { db } from '@/lib/db';
import { ajisAnak } from '@/db/schema';

export async function seedAnak() {
  console.log('👶 Seeding anak data...');

  // Anak data (3 per wilayah = 9 total)
  // Using hardcoded wilayah IDs that will be created by organization seed
  const anakData = [
    // Wilayah Jakarta Pusat (wilayah ID 1)
    {
      kodeAnak: 'ANK-JKT-001',
      nik: '3171234567890001',
      namaLengkap: 'Ahmad Fauzi',
      namaPanggilan: 'Fauzi',
      agama: 'Islam',
      jnsKel: 'L',
      tempatLahir: 'Jakarta',
      tglLahir: '2012-05-15',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Sudirman No. 123, Jakarta Pusat',
      desaId: 1,
      jenjangPendidikan: 'SD',
      kelas: '5',
      namaSekolah: 'SDN Gambir 01',
      alamatSekolah: 'Jl. Gambir No. 1, Jakarta Pusat',
      noRekening: '1234567890',
      pemilikRekening: 'Ahmad Fauzi',
      namaBank: 'BCA',
      nilai: 'A',
      pelajaranFavorit: 'Matematika',
      jarakRumah: '2 km',
      alatTransportasi: 'Motor',
      hobi: 'Sepak bola',
      prestasi: 'Juara 1 Lomba Matematika Sekolah',
      noKartuKeluarga: '3171234567890001',
      asnaf: 'Dhuafa',
      statusOrtu: 'Yatim Piatu',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: 1,
      kantorId: 1,
      namaMentorManual: 'Budi Santoso',
      tglTerdaftar: '2020-01-15',
      tglPengajuan: '2020-01-10',
      namaLengkapAyah: 'Ahmad Hidayat',
      alamatAyah: 'Jl. Sudirman No. 123, Jakarta Pusat',
      pekerjaanAyah: 'Wiraswasta',
      penghasilanAyah: '2000000.00',
      tglKematianAyah: '2018-06-20',
      penyebabKematianAyah: 'Sakit',
      namaLengkapIbu: 'Siti Aminah',
      alamatIbu: 'Jl. Sudirman No. 123, Jakarta Pusat',
      pekerjaanIbu: 'Ibu Rumah Tangga',
      penghasilanIbu: '1500000.00',
      tglKematianIbu: '2019-03-15',
      penyebabKematianIbu: 'Kecelakaan',
      namaLengkapWali: 'H. Abdullah',
      alamatWali: 'Jl. Sudirman No. 124, Jakarta Pusat',
      pekerjaanWali: 'Pedagang',
      penghasilanWali: '3000000.00',
      telpDihubungi: '081234567890',
      atasNama: 'H. Abdullah',
      hubunganKerabat: 'Paman',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-JKT',
      tinggalBersama: 'Paman',
      namaTinggal: 'H. Abdullah',
      ketTinggal: 'Tinggal bersama paman sejak yatim piatu',
      penghasilanTinggal: '3000000',
      pekerjaanTinggal: 'Pedagang',
      tidakSerumahOrtu: 'y',
    },
    // Wilayah Cibinong (wilayah ID 4)
    {
      kodeAnak: 'ANK-BDG-001',
      nik: '3201234567890001',
      namaLengkap: 'Rina Melati',
      namaPanggilan: 'Melati',
      agama: 'Islam',
      jnsKel: 'P',
      tempatLahir: 'Bogor',
      tglLahir: '2011-12-01',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Raya Cibinong No. 200, Cibinong',
      desaId: 4,
      jenjangPendidikan: 'SMP',
      kelas: '8',
      namaSekolah: 'SMPN 1 Cibinong',
      alamatSekolah: 'Jl. Raya Cibinong No. 50, Cibinong',
      noRekening: '5566778899',
      pemilikRekening: 'Rina Melati',
      namaBank: 'BRI',
      nilai: 'A',
      pelajaranFavorit: 'Matematika',
      jarakRumah: '1 km',
      alatTransportasi: 'Motor',
      hobi: 'Menari',
      prestasi: 'Juara 1 Lomba Tari Daerah',
      noKartuKeluarga: '3201234567890001',
      asnaf: 'Yatim',
      statusOrtu: 'Yatim',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: 4,
      kantorId: 2,
      namaMentorManual: 'Siti Aminah',
      tglTerdaftar: '2020-04-10',
      tglPengajuan: '2020-04-05',
      namaLengkapAyah: 'Hendro Wibowo',
      alamatAyah: 'Jl. Raya Cibinong No. 200, Cibinong',
      pekerjaanAyah: 'Petani',
      penghasilanAyah: '1500000.00',
      tglKematianAyah: '2016-08-15',
      penyebabKematianAyah: 'Kecelakaan Kerja',
      namaLengkapIbu: 'Sri Wahyuni',
      alamatIbu: 'Jl. Raya Cibinong No. 200, Cibinong',
      pekerjaanIbu: 'Buruh Tani',
      penghasilanIbu: '1000000.00',
      telpDihubungi: '081234567893',
      atasNama: 'Sri Wahyuni',
      hubunganKerabat: 'Ibu',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-BDG',
      tinggalBersama: 'Ibu',
      namaTinggal: 'Sri Wahyuni',
      ketTinggal: 'Tinggal bersama ibu',
      penghasilanTinggal: '1000000',
      pekerjaanTinggal: 'Buruh Tani',
      tidakSerumahOrtu: 'n',
    },
    // Wilayah Johan Pahlawan (wilayah ID 7)
    {
      kodeAnak: 'ANK-ACEH-001',
      nik: '1101234567890001',
      namaLengkap: 'Teuku Rizky',
      namaPanggilan: 'Rizky',
      agama: 'Islam',
      jnsKel: 'L',
      tempatLahir: 'Meulaboh',
      tglLahir: '2010-04-12',
      anakKe: 1,
      dariSaudara: 2,
      alamat: 'Jl. Johan Pahlawan No. 50, Meulaboh',
      desaId: 7,
      jenjangPendidikan: 'SMA',
      kelas: '11',
      namaSekolah: 'SMA Negeri 1 Johan Pahlawan',
      alamatSekolah: 'Jl. Johan Pahlawan No. 10, Meulaboh',
      noRekening: '3344556677',
      pemilikRekening: 'Teuku Rizky',
      namaBank: 'BRI Syariah',
      nilai: 'A',
      pelajaranFavorit: 'Fisika',
      jarakRumah: '3 km',
      alatTransportasi: 'Motor',
      hobi: 'Renang',
      prestasi: 'Juara 1 Lomba Renang Provinsi',
      noKartuKeluarga: '1101234567890001',
      asnaf: 'Dhuafa',
      statusOrtu: 'Kedua Orang Tua Hidup',
      statusSurvey: 'y',
      statusKelayakan: 'y',
      statusAnakJuara: 'ya',
      statusTersantuni: 'su',
      statusPinjam: 'n',
      statusMentor: 'y',
      aktif: 'y',
      alumniJuara: 'n',
      juara: 'ya',
      wilayahPembinaanId: 7,
      kantorId: 3,
      namaMentorManual: 'Teuku Iskandar',
      tglTerdaftar: '2020-07-10',
      tglPengajuan: '2020-07-05',
      namaLengkapAyah: 'Teuku Ibrahim',
      alamatAyah: 'Jl. Johan Pahlawan No. 50, Meulaboh',
      pekerjaanAyah: 'Nelayan',
      penghasilanAyah: '2500000.00',
      namaLengkapIbu: 'Cut Nyak Meutia',
      alamatIbu: 'Jl. Johan Pahlawan No. 50, Meulaboh',
      pekerjaanIbu: 'Penjual Ikan',
      penghasilanIbu: '2000000.00',
      telpDihubungi: '081234567896',
      atasNama: 'Teuku Ibrahim',
      hubunganKerabat: 'Ayah',
      viaInput: 'Manual',
      approvalIjf: 'y',
      kodeProgramRz: 'RZ-ACEH',
      tinggalBersama: 'Orang Tua',
      namaTinggal: 'Teuku Ibrahim',
      ketTinggal: 'Tinggal bersama orang tua',
      penghasilanTinggal: '4500000',
      pekerjaanTinggal: 'Nelayan',
      tidakSerumahOrtu: 'n',
    },
  ];

  const insertedAnak = await db.insert(ajisAnak).values(anakData).returning();
  console.log(`✅ Inserted ${insertedAnak.length} anak`);

  return insertedAnak;
}
