import { donatur } from '@/lib/db/schema';
import { db } from '@/lib/repositories/base.repository';

export async function seedDonatur() {
  console.log('🌱 Seeding donatur...');

  const donaturData = [
    {
      kodeLama: 'D001',
      namaLengkap: 'Ahmad Hidayat',
      namaPublikasi: 'Ahmad Hidayat',
      tglLahir: '1980-05-15',
      jenisKelamin: 'l',
      alamatLengkap: 'Jl. Merdeka No. 123, Jakarta Pusat',
      alamatSilaturahmi: null,
      kecamatanDomisiliId: null,
      kecamatanSilaturahmiId: null,
      statusDonatur: 'individu',
      tglRegistrasi: '2020-01-01',
      aktif: 'y',
      kirimSms: 'y',
      telp: '021-12345678',
      fax: null,
      hp: '081234567890',
      email: 'ahmad@example.com',
      website: null,
      verifikasi1: true,
      verifikasi2: true,
      namaKontak: 'Ahmad Hidayat',
      telpKontak: '081234567890',
      emailKontak: 'ahmad@example.com',
      jabatanKontak: null,
      namaBank: 'BCA',
      noRekening: '1234567890',
      kantorDonaturId: null,
      niaRfo: null,
      namaRfo: null,
      tipePelayanan: null,
      npwp: null,
      userInsert: 'seed',
      dateInsert: new Date(),
    },
    {
      kodeLama: 'D002',
      namaLengkap: 'PT. Sejahtera Abadi',
      namaPublikasi: 'PT. Sejahtera Abadi',
      tglLahir: null,
      jenisKelamin: 't',
      alamatLengkap: 'Jl. Sudirman No. 456, Jakarta Selatan',
      alamatSilaturahmi: null,
      kecamatanDomisiliId: null,
      kecamatanSilaturahmiId: null,
      statusDonatur: 'corporate',
      tglRegistrasi: '2020-02-01',
      aktif: 'y',
      kirimSms: 'n',
      telp: '021-98765432',
      fax: '021-98765433',
      hp: null,
      email: 'info@sejahteraabadi.co.id',
      website: 'www.sejahteraabadi.co.id',
      verifikasi1: true,
      verifikasi2: true,
      namaKontak: 'Budi Santoso',
      telpKontak: '081987654321',
      emailKontak: 'budi@sejahteraabadi.co.id',
      jabatanKontak: 'Manager',
      namaBank: 'Mandiri',
      noRekening: '0987654321',
      kantorDonaturId: null,
      niaRfo: null,
      namaRfo: null,
      tipePelayanan: null,
      npwp: '01.234.567.8-901.000',
      userInsert: 'seed',
      dateInsert: new Date(),
    },
    {
      kodeLama: 'D003',
      namaLengkap: 'Siti Aminah',
      namaPublikasi: 'Siti Aminah',
      tglLahir: '1985-08-20',
      jenisKelamin: 'p',
      alamatLengkap: 'Jl. Gatot Subroto No. 789, Bandung',
      alamatSilaturahmi: null,
      kecamatanDomisiliId: null,
      kecamatanSilaturahmiId: null,
      statusDonatur: 'individu',
      tglRegistrasi: '2020-03-01',
      aktif: 'y',
      kirimSms: 'y',
      telp: '022-34567890',
      fax: null,
      hp: '082345678901',
      email: 'siti@example.com',
      website: null,
      verifikasi1: true,
      verifikasi2: false,
      namaKontak: 'Siti Aminah',
      telpKontak: '082345678901',
      emailKontak: 'siti@example.com',
      jabatanKontak: null,
      namaBank: 'BRI',
      noRekening: '2345678901',
      kantorDonaturId: null,
      niaRfo: null,
      namaRfo: null,
      tipePelayanan: null,
      npwp: null,
      userInsert: 'seed',
      dateInsert: new Date(),
    },
    {
      kodeLama: 'D004',
      namaLama: 'Yayasan Berkah',
      namaLengkap: 'Yayasan Berkah',
      namaPublikasi: 'Yayasan Berkah',
      tglLahir: null,
      jenisKelamin: 't',
      alamatLengkap: 'Jl. Diponegoro No. 100, Surabaya',
      alamatSilaturahmi: null,
      kecamatanDomisiliId: null,
      kecamatanSilaturahmiId: null,
      statusDonatur: 'yayasan',
      tglRegistrasi: '2020-04-01',
      aktif: 'y',
      kirimSms: 'n',
      telp: '031-23456789',
      fax: null,
      hp: null,
      email: 'info@yayasanberkah.org',
      website: 'www.yayasanberkah.org',
      verifikasi1: true,
      verifikasi2: true,
      namaKontak: 'Drs. H. Abdullah',
      telpKontak: '083456789012',
      emailKontak: 'abdullah@yayasanberkah.org',
      jabatanKontak: 'Ketua Yayasan',
      namaBank: 'BSI',
      noRekening: '3456789012',
      kantorDonaturId: null,
      niaRfo: null,
      namaRfo: null,
      tipePelayanan: null,
      npwp: '02.345.678.9-012.000',
      userInsert: 'seed',
      dateInsert: new Date(),
    },
    {
      kodeLama: 'D005',
      namaLengkap: 'Masjid Al-Falah',
      namaPublikasi: 'Masjid Al-Falah',
      tglLahir: null,
      jenisKelamin: 't',
      alamatLengkap: 'Jl. Pahlawan Revolusi No. 50, Bekasi',
      alamatSilaturahmi: null,
      kecamatanDomisiliId: null,
      kecamatanSilaturahmiId: null,
      statusDonatur: 'masjid',
      tglRegistrasi: '2020-05-01',
      aktif: 'y',
      kirimSms: 'n',
      telp: '021-88776655',
      fax: null,
      hp: null,
      email: 'masjid@alfalah.or.id',
      website: null,
      verifikasi1: true,
      verifikasi2: true,
      namaKontak: 'Ust. Ahmad Fauzi',
      telpKontak: '084567890123',
      emailKontak: 'ustadz@alfalah.or.id',
      jabatanKontak: 'Ketua DKM',
      namaBank: 'Muamalat',
      noRekening: '4567890123',
      kantorDonaturId: null,
      niaRfo: null,
      namaRfo: null,
      tipePelayanan: null,
      npwp: null,
      userInsert: 'seed',
      dateInsert: new Date(),
    },
  ];

  try {
    // Check if donatur already exist
    const existing = await db.select().from(donatur).limit(1);
    if (existing.length > 0) {
      console.log('✓ Donatur already exist, skipping seed');
      return;
    }

    // Insert donatur
    await db.insert(donatur).values(donaturData);
    console.log(`✓ Seeded ${donaturData.length} donatur`);
  } catch (error) {
    console.error('Error seeding donatur:', error);
    throw error;
  }
}
