import { db } from '@/lib/db';
import { ajisSdmWilayah } from '@/db/schema';

export async function seedSdm() {
  console.log('👥 Seeding SDM data...');

  // SDM Wilayah data (3 per wilayah = 9 total)
  // Using hardcoded wilayah IDs that will be created by organization seed
  const sdmData = [
    // Jakarta Pusat (wilayah ID 1)
    {
      kodeLama: 1,
      nik: '3171234567890010',
      namaLengkap: 'Budi Santoso',
      jenisKelamin: 'l',
      alamat: 'Jl. Sudirman No. 100, Jakarta Pusat',
      jenjangPendidikan: 'S1',
      tglBergabung: '2019-01-15',
      telp: '021-12345678',
      hp: '081234567800',
      email: 'budi.santoso@rz-ajis.com',
      keterangan: 'SDM Wilayah Jakarta Pusat',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 1,
      penugasanKantorId: 1,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
    // Jakarta Selatan (wilayah ID 2)
    {
      kodeLama: 2,
      nik: '3171234567890011',
      namaLengkap: 'Dewi Kartika',
      jenisKelamin: 'p',
      alamat: 'Jl. Fatmawati No. 50, Jakarta Selatan',
      jenjangPendidikan: 'S1',
      tglBergabung: '2019-02-20',
      telp: '021-87654321',
      hp: '081234567801',
      email: 'dewi.kartika@rz-ajis.com',
      keterangan: 'SDM Wilayah Jakarta Selatan',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 2,
      penugasanKantorId: 1,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
    // Jakarta Barat (wilayah ID 3)
    {
      kodeLama: 3,
      nik: '3171234567890012',
      namaLengkap: 'Agus Setiawan',
      jenisKelamin: 'l',
      alamat: 'Jl. Palmerah No. 30, Jakarta Barat',
      jenjangPendidikan: 'D3',
      tglBergabung: '2019-03-25',
      telp: '021-11122233',
      hp: '081234567802',
      email: 'agus.setiawan@rz-ajis.com',
      keterangan: 'SDM Wilayah Jakarta Barat',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 3,
      penugasanKantorId: 1,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
    // Cibinong (wilayah ID 4)
    {
      kodeLama: 4,
      nik: '3201234567890010',
      namaLengkap: 'Siti Aminah',
      jenisKelamin: 'p',
      alamat: 'Jl. Raya Cibinong No. 150, Cibinong',
      jenjangPendidikan: 'S1',
      tglBergabung: '2019-04-10',
      telp: '021-44455566',
      hp: '081234567803',
      email: 'siti.aminah@rz-ajis.com',
      keterangan: 'SDM Wilayah Cibinong',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 4,
      penugasanKantorId: 2,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
    // Citeureup (wilayah ID 5)
    {
      kodeLama: 5,
      nik: '3201234567890011',
      namaLengkap: 'Joko Susilo',
      jenisKelamin: 'l',
      alamat: 'Jl. Citeureup No. 100, Citeureup',
      jenjangPendidikan: 'SMA',
      tglBergabung: '2019-05-15',
      telp: '021-77788899',
      hp: '081234567804',
      email: 'joko.susilo@rz-ajis.com',
      keterangan: 'SDM Wilayah Citeureup',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 5,
      penugasanKantorId: 2,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
    // Gunung Putri (wilayah ID 6)
    {
      kodeLama: 6,
      nik: '3201234567890012',
      namaLengkap: 'Ratna Sari',
      jenisKelamin: 'p',
      alamat: 'Jl. Gunung Putri No. 50, Gunung Putri',
      jenjangPendidikan: 'S1',
      tglBergabung: '2019-06-20',
      telp: '021-99900011',
      hp: '081234567805',
      email: 'ratna.sari@rz-ajis.com',
      keterangan: 'SDM Wilayah Gunung Putri',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 6,
      penugasanKantorId: 2,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
    // Johan Pahlawan (wilayah ID 7)
    {
      kodeLama: 7,
      nik: '1101234567890010',
      namaLengkap: 'Teuku Iskandar',
      jenisKelamin: 'l',
      alamat: 'Jl. Johan Pahlawan No. 30, Meulaboh',
      jenjangPendidikan: 'S1',
      tglBergabung: '2019-07-10',
      telp: '0651-111222',
      hp: '081234567806',
      email: 'teuku.iskandar@rz-ajis.com',
      keterangan: 'SDM Wilayah Johan Pahlawan',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 7,
      penugasanKantorId: 3,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
    // Jantho (wilayah ID 8)
    {
      kodeLama: 8,
      nik: '1101234567890011',
      namaLengkap: 'Siti Sarah',
      jenisKelamin: 'p',
      alamat: 'Jl. Jantho No. 50, Jantho',
      jenjangPendidikan: 'D3',
      tglBergabung: '2019-08-15',
      telp: '0651-333444',
      hp: '081234567807',
      email: 'siti.sarah@rz-ajis.com',
      keterangan: 'SDM Wilayah Jantho',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 8,
      penugasanKantorId: 3,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
    // Samatiga (wilayah ID 9)
    {
      kodeLama: 9,
      nik: '1101234567890012',
      namaLengkap: 'Abdullah',
      jenisKelamin: 'l',
      alamat: 'Jl. Samatiga No. 30, Samatiga',
      jenjangPendidikan: 'SMA',
      tglBergabung: '2019-09-20',
      telp: '0651-555666',
      hp: '081234567808',
      email: 'abdullah@rz-ajis.com',
      keterangan: 'SDM Wilayah Samatiga',
      keaktifanEdukasi: 'y',
      penugasanWilayahId: 9,
      penugasanKantorId: 3,
      penugasanFungsiStruktur: 'Mentor',
      penugasanKeaktifanEdukasi: 'y',
      aktif: 'y',
      userInsert: 'seed',
      dateInsert: new Date().toISOString(),
    },
  ];

  const insertedSdm = await db.insert(ajisSdmWilayah).values(sdmData).returning();
  console.log(`✅ Inserted ${insertedSdm.length} SDM wilayah`);

  return insertedSdm;
}
