/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWilayahRouteImport } from './routes/dashboard.wilayah'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSurveyRouteImport } from './routes/dashboard.survey'
import { Route as DashboardStatistikRouteImport } from './routes/dashboard.statistik'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSesiRouteImport } from './routes/dashboard.sesi'
import { Route as DashboardSdmRouteImport } from './routes/dashboard.sdm'
import { Route as DashboardPropinsiRouteImport } from './routes/dashboard.propinsi'
import { Route as DashboardLaporanRouteImport } from './routes/dashboard.laporan'
import { Route as DashboardKecamatanRouteImport } from './routes/dashboard.kecamatan'
import { Route as DashboardKantorRouteImport } from './routes/dashboard.kantor'
import { Route as DashboardKabupatenRouteImport } from './routes/dashboard.kabupaten'
import { Route as DashboardJabatanRouteImport } from './routes/dashboard.jabatan'
import { Route as DashboardHafalanRouteImport } from './routes/dashboard.hafalan'
import { Route as DashboardGroupUserRouteImport } from './routes/dashboard.group-user'
import { Route as DashboardEvaluasiRouteImport } from './routes/dashboard.evaluasi'
import { Route as DashboardDesaRouteImport } from './routes/dashboard.desa'
import { Route as DashboardAnakRouteImport } from './routes/dashboard.anak'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWilayahRoute = DashboardWilayahRouteImport.update({
  id: '/wilayah',
  path: '/wilayah',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSurveyRoute = DashboardSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatistikRoute = DashboardStatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSesiRoute = DashboardSesiRouteImport.update({
  id: '/sesi',
  path: '/sesi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSdmRoute = DashboardSdmRouteImport.update({
  id: '/sdm',
  path: '/sdm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropinsiRoute = DashboardPropinsiRouteImport.update({
  id: '/propinsi',
  path: '/propinsi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLaporanRoute = DashboardLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKecamatanRoute = DashboardKecamatanRouteImport.update({
  id: '/kecamatan',
  path: '/kecamatan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKantorRoute = DashboardKantorRouteImport.update({
  id: '/kantor',
  path: '/kantor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKabupatenRoute = DashboardKabupatenRouteImport.update({
  id: '/kabupaten',
  path: '/kabupaten',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJabatanRoute = DashboardJabatanRouteImport.update({
  id: '/jabatan',
  path: '/jabatan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHafalanRoute = DashboardHafalanRouteImport.update({
  id: '/hafalan',
  path: '/hafalan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupUserRoute = DashboardGroupUserRouteImport.update({
  id: '/group-user',
  path: '/group-user',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvaluasiRoute = DashboardEvaluasiRouteImport.update({
  id: '/evaluasi',
  path: '/evaluasi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDesaRoute = DashboardDesaRouteImport.update({
  id: '/desa',
  path: '/desa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnakRoute = DashboardAnakRouteImport.update({
  id: '/anak',
  path: '/anak',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/anak': typeof DashboardAnakRoute
  '/dashboard/desa': typeof DashboardDesaRoute
  '/dashboard/evaluasi': typeof DashboardEvaluasiRoute
  '/dashboard/group-user': typeof DashboardGroupUserRoute
  '/dashboard/hafalan': typeof DashboardHafalanRoute
  '/dashboard/jabatan': typeof DashboardJabatanRoute
  '/dashboard/kabupaten': typeof DashboardKabupatenRoute
  '/dashboard/kantor': typeof DashboardKantorRoute
  '/dashboard/kecamatan': typeof DashboardKecamatanRoute
  '/dashboard/laporan': typeof DashboardLaporanRoute
  '/dashboard/propinsi': typeof DashboardPropinsiRoute
  '/dashboard/sdm': typeof DashboardSdmRoute
  '/dashboard/sesi': typeof DashboardSesiRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statistik': typeof DashboardStatistikRoute
  '/dashboard/survey': typeof DashboardSurveyRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/wilayah': typeof DashboardWilayahRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/anak': typeof DashboardAnakRoute
  '/dashboard/desa': typeof DashboardDesaRoute
  '/dashboard/evaluasi': typeof DashboardEvaluasiRoute
  '/dashboard/group-user': typeof DashboardGroupUserRoute
  '/dashboard/hafalan': typeof DashboardHafalanRoute
  '/dashboard/jabatan': typeof DashboardJabatanRoute
  '/dashboard/kabupaten': typeof DashboardKabupatenRoute
  '/dashboard/kantor': typeof DashboardKantorRoute
  '/dashboard/kecamatan': typeof DashboardKecamatanRoute
  '/dashboard/laporan': typeof DashboardLaporanRoute
  '/dashboard/propinsi': typeof DashboardPropinsiRoute
  '/dashboard/sdm': typeof DashboardSdmRoute
  '/dashboard/sesi': typeof DashboardSesiRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statistik': typeof DashboardStatistikRoute
  '/dashboard/survey': typeof DashboardSurveyRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/wilayah': typeof DashboardWilayahRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/anak': typeof DashboardAnakRoute
  '/dashboard/desa': typeof DashboardDesaRoute
  '/dashboard/evaluasi': typeof DashboardEvaluasiRoute
  '/dashboard/group-user': typeof DashboardGroupUserRoute
  '/dashboard/hafalan': typeof DashboardHafalanRoute
  '/dashboard/jabatan': typeof DashboardJabatanRoute
  '/dashboard/kabupaten': typeof DashboardKabupatenRoute
  '/dashboard/kantor': typeof DashboardKantorRoute
  '/dashboard/kecamatan': typeof DashboardKecamatanRoute
  '/dashboard/laporan': typeof DashboardLaporanRoute
  '/dashboard/propinsi': typeof DashboardPropinsiRoute
  '/dashboard/sdm': typeof DashboardSdmRoute
  '/dashboard/sesi': typeof DashboardSesiRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statistik': typeof DashboardStatistikRoute
  '/dashboard/survey': typeof DashboardSurveyRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/wilayah': typeof DashboardWilayahRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/anak'
    | '/dashboard/desa'
    | '/dashboard/evaluasi'
    | '/dashboard/group-user'
    | '/dashboard/hafalan'
    | '/dashboard/jabatan'
    | '/dashboard/kabupaten'
    | '/dashboard/kantor'
    | '/dashboard/kecamatan'
    | '/dashboard/laporan'
    | '/dashboard/propinsi'
    | '/dashboard/sdm'
    | '/dashboard/sesi'
    | '/dashboard/settings'
    | '/dashboard/statistik'
    | '/dashboard/survey'
    | '/dashboard/users'
    | '/dashboard/wilayah'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/anak'
    | '/dashboard/desa'
    | '/dashboard/evaluasi'
    | '/dashboard/group-user'
    | '/dashboard/hafalan'
    | '/dashboard/jabatan'
    | '/dashboard/kabupaten'
    | '/dashboard/kantor'
    | '/dashboard/kecamatan'
    | '/dashboard/laporan'
    | '/dashboard/propinsi'
    | '/dashboard/sdm'
    | '/dashboard/sesi'
    | '/dashboard/settings'
    | '/dashboard/statistik'
    | '/dashboard/survey'
    | '/dashboard/users'
    | '/dashboard/wilayah'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/anak'
    | '/dashboard/desa'
    | '/dashboard/evaluasi'
    | '/dashboard/group-user'
    | '/dashboard/hafalan'
    | '/dashboard/jabatan'
    | '/dashboard/kabupaten'
    | '/dashboard/kantor'
    | '/dashboard/kecamatan'
    | '/dashboard/laporan'
    | '/dashboard/propinsi'
    | '/dashboard/sdm'
    | '/dashboard/sesi'
    | '/dashboard/settings'
    | '/dashboard/statistik'
    | '/dashboard/survey'
    | '/dashboard/users'
    | '/dashboard/wilayah'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wilayah': {
      id: '/dashboard/wilayah'
      path: '/wilayah'
      fullPath: '/dashboard/wilayah'
      preLoaderRoute: typeof DashboardWilayahRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/survey': {
      id: '/dashboard/survey'
      path: '/survey'
      fullPath: '/dashboard/survey'
      preLoaderRoute: typeof DashboardSurveyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/statistik': {
      id: '/dashboard/statistik'
      path: '/statistik'
      fullPath: '/dashboard/statistik'
      preLoaderRoute: typeof DashboardStatistikRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sesi': {
      id: '/dashboard/sesi'
      path: '/sesi'
      fullPath: '/dashboard/sesi'
      preLoaderRoute: typeof DashboardSesiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sdm': {
      id: '/dashboard/sdm'
      path: '/sdm'
      fullPath: '/dashboard/sdm'
      preLoaderRoute: typeof DashboardSdmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/propinsi': {
      id: '/dashboard/propinsi'
      path: '/propinsi'
      fullPath: '/dashboard/propinsi'
      preLoaderRoute: typeof DashboardPropinsiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/laporan': {
      id: '/dashboard/laporan'
      path: '/laporan'
      fullPath: '/dashboard/laporan'
      preLoaderRoute: typeof DashboardLaporanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kecamatan': {
      id: '/dashboard/kecamatan'
      path: '/kecamatan'
      fullPath: '/dashboard/kecamatan'
      preLoaderRoute: typeof DashboardKecamatanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kantor': {
      id: '/dashboard/kantor'
      path: '/kantor'
      fullPath: '/dashboard/kantor'
      preLoaderRoute: typeof DashboardKantorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kabupaten': {
      id: '/dashboard/kabupaten'
      path: '/kabupaten'
      fullPath: '/dashboard/kabupaten'
      preLoaderRoute: typeof DashboardKabupatenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jabatan': {
      id: '/dashboard/jabatan'
      path: '/jabatan'
      fullPath: '/dashboard/jabatan'
      preLoaderRoute: typeof DashboardJabatanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hafalan': {
      id: '/dashboard/hafalan'
      path: '/hafalan'
      fullPath: '/dashboard/hafalan'
      preLoaderRoute: typeof DashboardHafalanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/group-user': {
      id: '/dashboard/group-user'
      path: '/group-user'
      fullPath: '/dashboard/group-user'
      preLoaderRoute: typeof DashboardGroupUserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evaluasi': {
      id: '/dashboard/evaluasi'
      path: '/evaluasi'
      fullPath: '/dashboard/evaluasi'
      preLoaderRoute: typeof DashboardEvaluasiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/desa': {
      id: '/dashboard/desa'
      path: '/desa'
      fullPath: '/dashboard/desa'
      preLoaderRoute: typeof DashboardDesaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/anak': {
      id: '/dashboard/anak'
      path: '/anak'
      fullPath: '/dashboard/anak'
      preLoaderRoute: typeof DashboardAnakRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnakRoute: typeof DashboardAnakRoute
  DashboardDesaRoute: typeof DashboardDesaRoute
  DashboardEvaluasiRoute: typeof DashboardEvaluasiRoute
  DashboardGroupUserRoute: typeof DashboardGroupUserRoute
  DashboardHafalanRoute: typeof DashboardHafalanRoute
  DashboardJabatanRoute: typeof DashboardJabatanRoute
  DashboardKabupatenRoute: typeof DashboardKabupatenRoute
  DashboardKantorRoute: typeof DashboardKantorRoute
  DashboardKecamatanRoute: typeof DashboardKecamatanRoute
  DashboardLaporanRoute: typeof DashboardLaporanRoute
  DashboardPropinsiRoute: typeof DashboardPropinsiRoute
  DashboardSdmRoute: typeof DashboardSdmRoute
  DashboardSesiRoute: typeof DashboardSesiRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatistikRoute: typeof DashboardStatistikRoute
  DashboardSurveyRoute: typeof DashboardSurveyRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWilayahRoute: typeof DashboardWilayahRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnakRoute: DashboardAnakRoute,
  DashboardDesaRoute: DashboardDesaRoute,
  DashboardEvaluasiRoute: DashboardEvaluasiRoute,
  DashboardGroupUserRoute: DashboardGroupUserRoute,
  DashboardHafalanRoute: DashboardHafalanRoute,
  DashboardJabatanRoute: DashboardJabatanRoute,
  DashboardKabupatenRoute: DashboardKabupatenRoute,
  DashboardKantorRoute: DashboardKantorRoute,
  DashboardKecamatanRoute: DashboardKecamatanRoute,
  DashboardLaporanRoute: DashboardLaporanRoute,
  DashboardPropinsiRoute: DashboardPropinsiRoute,
  DashboardSdmRoute: DashboardSdmRoute,
  DashboardSesiRoute: DashboardSesiRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatistikRoute: DashboardStatistikRoute,
  DashboardSurveyRoute: DashboardSurveyRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWilayahRoute: DashboardWilayahRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
